plugins {
    id 'org.moddingx.modgradle.meta' version '5.0.3'
}

repositories {
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev/'
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var baseVersion = '21.3'
var modBaseVersion = '1.21.3-5.1'

mod.configure {
    modid 'defaultworldtype'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base modBaseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge project.hasProperty('neo_version') ? project.neo_version : "${baseVersion}.0-beta"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/DefaultWorldType'

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type 'beta'
            version '1.21.3'
            version '1.21.4'
            version '1.21.5'
        }
        curseforge {
            projectId 373014
        }
        modrinth {
            projectId 'kZvO1mDq'
        }
    }
}
