plugins {
    id 'org.moddingx.modgradle.meta' version '5.1.0'
}

repositories {
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev/'
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var releaseType = 'beta'
var baseVersion = '26.1'

mod.configure {
    modid 'defaultworldtype'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge "${baseVersion}.0.1-beta"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/DefaultWorldType'

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type releaseType
            version '26.1'
            version '26.1.1'
            version '26.1.2'
        }
        curseforge {
            projectId 373014
        }
        modrinth {
            projectId 'kZvO1mDq'
        }
    }
}
