modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"

[[mods]]
modId="defaultworldtype"
version="${file.jarVersion}"
displayName="Default World Type"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/defaultworldtype.json"
credits="Thanks for Biomes O' Plenty for the idea."
authors="MelanX"
description='''
Changes the default world type to that one specified in config.
'''

[[dependencies.defaultworldtype]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.defaultworldtype]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="CLIENT"
