modLoader="javafml"
loaderVersion="[41,)"
license="Apache 2.0"

[[mods]]
modId="defaultworldtype"
version="${file.jarVersion}"
displayName="Default World Type"
updateJSONURL="https://assets.melanx.de/updates/defaultworldtype.json"
credits="Thanks for Biomes O' Plenty for the idea."
authors="MelanX"
displayTest="IGNORE_ALL_VERSION"
description='''
Changes the default world type to that one specified in config.
'''

[[dependencies.defaultworldtype]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.defaultworldtype]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="CLIENT"
