modLoader="javafml"
loaderVersion="[${fml},)"
license="Apache 2.0"
issueTrackerURL="https://www.github.com/MelanX/DefaultWorldType/issues/"

[[mods]]
modId="defaultworldtype"
version="${version}"
displayName="Default World Type"
updateJSONURL="https://assets.melanx.de/updates/defaultworldtype.json"
credits="Thanks for Biomes O' Plenty for the idea."
authors="MelanX"
displayTest="IGNORE_ALL_VERSION"
description='''
Changes the default world type to that one specified in config.
'''

[[dependencies.defaultworldtype]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.defaultworldtype]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="CLIENT"
