modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod.license}"
issueTrackerURL = "${mod.issue_url}"

[[mods]]
modId = "${mod.modid}"
version = "${mod.version}"
displayURL = "${mod.source_url}"
displayName = "Default World Type"
updateJSONURL = "https://assets.melanx.de/updates/defaultworldtype.json"
authors = "MelanX"
description = """
Change the default world type for creating a new world in Create World screen
"""

[[mixins]]
config = "${mod.modid}.mixins.json"

[[dependencies.${ mod.modid }]]
   modId = "neoforge"
   type = "required"
versionRange = "[${mod.neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod.modid }]]
modId = "minecraft"
type = "required"
versionRange = "[${mod.minecraft},)"
ordering = "NONE"
side = "BOTH"
